create table if not exists public.guild_intelligence_page_registry (
  page_key text primary key,
  workbook_sheet text not null unique,
  title text not null,
  category text not null,
  source_kind text not null,
  implementation_status text not null check (implementation_status in ('active','partial','pending_source','legacy_reference')),
  phase smallint not null default 1 check (phase between 1 and 9),
  daily_capture boolean not null default true,
  user_facing boolean not null default true,
  sort_order smallint not null,
  description text not null default '',
  expected_sources text[] not null default '{}'::text[],
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.guild_intelligence_settings (
  guild_id uuid primary key references public.guilds(id) on delete cascade,
  enabled boolean not null default true,
  report_timezone text not null default 'America/Phoenix',
  report_local_time time not null default '00:00:00',
  last_enqueued_report_date date,
  last_enqueued_at timestamptz,
  last_completed_report_date date,
  last_completed_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guild_intelligence_daily_reports (
  id uuid primary key default gen_random_uuid(),
  guild_id uuid not null references public.guilds(id) on delete cascade,
  report_date date not null,
  report_timezone text not null,
  scheduled_local_time time not null default '00:00:00',
  status text not null default 'queued' check (status in ('queued','capturing','completed','partial','failed')),
  source_sync_job_id uuid references public.guild_sync_jobs(id) on delete set null,
  source_sync_run_id uuid references public.guild_sync_runs(id) on delete set null,
  captured_at timestamptz,
  completed_at timestamptz,
  summary jsonb not null default '{}'::jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (guild_id, report_date)
);

create table if not exists public.guild_intelligence_daily_pages (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.guild_intelligence_daily_reports(id) on delete cascade,
  guild_id uuid not null references public.guilds(id) on delete cascade,
  report_date date not null,
  page_key text not null references public.guild_intelligence_page_registry(page_key) on delete restrict,
  capture_status text not null check (capture_status in ('captured','partial','source_pending','not_applicable','failed')),
  captured_at timestamptz not null default now(),
  source_sync_run_id uuid references public.guild_sync_runs(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  error_message text,
  unique (report_id, page_key)
);

create table if not exists public.guild_member_absences (
  id uuid primary key default gen_random_uuid(),
  guild_id uuid not null references public.guilds(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  reason text not null default '',
  starts_at timestamptz not null,
  expected_return_at timestamptz,
  actual_return_at timestamptz,
  status text not null default 'planned' check (status in ('planned','active','returned','cancelled')),
  notes text not null default '',
  source text not null default 'officer',
  created_by_user_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guild_member_relationships (
  id uuid primary key default gen_random_uuid(),
  guild_id uuid not null references public.guilds(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  related_player_id uuid references public.players(id) on delete set null,
  relationship_type text not null default 'other',
  label text not null,
  notes text not null default '',
  source text not null default 'officer',
  created_by_user_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists guild_intelligence_reports_guild_date_idx on public.guild_intelligence_daily_reports(guild_id, report_date desc);
create index if not exists guild_intelligence_pages_guild_date_idx on public.guild_intelligence_daily_pages(guild_id, report_date desc, page_key);
create index if not exists guild_member_absences_guild_status_idx on public.guild_member_absences(guild_id, status, starts_at desc);
create index if not exists guild_member_relationships_guild_player_idx on public.guild_member_relationships(guild_id, player_id);

insert into public.guild_intelligence_page_registry
(page_key, workbook_sheet, title, category, source_kind, implementation_status, phase, daily_capture, user_facing, sort_order, description, expected_sources)
values
('gr_dashboard','GR Dashboard','Guild Roster Dashboard','Core Guild','canonical+derived','partial',1,true,true,1,'Guild health, movement, inactivity, GP, GL, ability and mod intelligence. Canonical roster/history is live; datacron and full mod-score parity remain later sources.',array['guild_snapshots','guild_members_current','guild_member_activity_snapshots','guild_membership_history','player_snapshots','player_units_current','mods','datacrons']),
('member_data','Member Data','Member Data','Core Guild','canonical','partial',1,true,true,2,'Daily per-member fact table: identity, join/activity, GP, GAC and contribution evidence. Arena and several workbook-only fields still require source parity.',array['players','guild_members_current','guild_member_activity_snapshots','player_snapshots']),
('zeffo','Zeffo','Zeffo Readiness','Territory Battles','roster-derived','pending_source',3,true,true,3,'Zeffo unlock/readiness tracking and required-unit progression.',array['player_units_current','zeffo_rules']),
('m_dashboard','M- Dashboard','ROTE Performance Dashboard','Territory Battles','event-derived','pending_source',3,true,true,4,'Selected ROTE event guild performance dashboard.',array['tb_event_history','tb_member_performance']),
('m_player_performance','M- Player Performance','ROTE Player Performance','Territory Battles','event-derived','pending_source',3,true,true,5,'Historical per-player ROTE deployment, waves, combat and Operations performance.',array['tb_event_history','tb_member_performance']),
('rote_data','ROTE Data','ROTE Raw Data','Territory Battles','event-raw','pending_source',3,true,false,6,'Normalized ROTE phase/player/mission contribution fact store.',array['tb_event_history','tb_mission_results']),
('scorecards','Scorecards','Officer Scorecards','Officer Intelligence','derived','partial',2,true,true,7,'Member responsibility scorecards combining activity, communication, tickets, Raid and ROTE evidence. Core activity is available; event-specific inputs are phased.',array['guild_member_activity_snapshots','guild_membership_history','raid_member_results','tb_member_performance','officer_notes']),
('raid_performance','Raid Performance','Raid Performance','Raids','event-derived','pending_source',4,true,true,8,'Per-player selected-raid score, participation, ticket and reward performance.',array['raid_events','raid_member_results']),
('raid_progress','Raid Progress','Raid Progress','Raids','event-derived','pending_source',4,true,true,9,'Historical Raid trends, averages, totals and progression.',array['raid_events','raid_member_results']),
('ticket_dashboard','Ticket Dashboard','Ticket Dashboard','Tickets & Activity','activity-derived','partial',2,true,true,10,'Guild ticket compliance dashboard. Member contribution evidence is persisted; exact daily ticket semantics need final source classification.',array['guild_member_activity_snapshots']),
('tickets','tickets','Ticket Detail','Tickets & Activity','activity-raw','partial',2,true,false,11,'Raw member ticket/activity rows used by the ticket dashboard.',array['guild_member_activity_snapshots']),
('rote_perf','ROTE Perf','ROTE Performance','Territory Battles','event-derived','pending_source',3,true,true,12,'Compact per-member ROTE event performance and combat metric.',array['tb_event_history','tb_member_performance']),
('rote_operations','ROTE Operations','ROTE Operations','Territory Battles','roster+rules','partial',2,true,true,13,'ROTE Operations/platoon requirements, owner coverage and assignments. Rules and roster tooling exist; server-side daily assignment persistence is phased.',array['player_units_current','rote_operation_rules','officer_assignments']),
('rote_summary','ROTE Summary','ROTE Summary','Territory Battles','event-derived','pending_source',3,true,true,14,'Per-event member ROTE totals, Operations GP, waves, GL and Reva context.',array['tb_event_history','tb_member_performance']),
('gl_report','GL Report','Galactic Legend Report','Roster Intelligence','canonical-derived','active',1,true,true,15,'Per-member Galactic Legend ownership and progression from canonical unit data.',array['player_units_current','game_units']),
('inquisitor_dashboard','Inquisitor Dashboard','Inquisitor / Reva Readiness','Roster Intelligence','canonical-derived','active',1,true,true,16,'Grand Inquisitor, Third Sister/Reva and Inquisitorius roster readiness.',array['player_units_current','game_units']),
('m_processing_cache','M- Processing Cache','Guild Intelligence Processing Cache','Internal','derived-cache','partial',1,true,false,17,'Internal derived processing state represented as report/snapshot provenance rather than a spreadsheet calculation cache.',array['guild_snapshots','guild_sync_runs']),
('member_data_backup','Member Data Backup','Member Daily History','Core Guild','canonical-history','active',1,true,false,18,'Durable daily player snapshots replacing workbook backup copies.',array['player_snapshots']),
('raid_history','Raid History','Raid History','Raids','event-history','pending_source',4,true,true,19,'Raid metadata timeline: tickets, start/end/reward timestamps, name and event ID.',array['raid_events']),
('raid_data','Raid Data','Raid Raw Data','Raids','event-raw','pending_source',4,true,false,20,'Per-event per-player Raid score fact table.',array['raid_member_results']),
('endor_perf_data','Endor Perf Data','Endor Historical Performance','Legacy Raid','legacy-import','legacy_reference',6,true,false,21,'Historical Endor Raid performance retained for import/reference; no new Endor daily event is expected.',array['legacy_workbook_import']),
('rote_reva','ROTE Reva','Reva Mission Performance','Territory Battles','event-derived','pending_source',3,true,true,22,'Per-event Reva mission attempts, score and guild completions.',array['tb_event_history','tb_mission_results']),
('absences','Absences','Member Absences','People Intelligence','officer-managed','active',1,true,true,23,'Officer-managed absence, expected return and actual return tracking.',array['guild_member_absences']),
('rote_platoons','ROTE Platoons','ROTE Platoons','Territory Battles','event+assignment','pending_source',3,true,true,24,'ROTE platoon/Operations fill matrix by phase, planet, platoon, cell, unit and player.',array['rote_operation_rules','officer_assignments','tb_event_state']),
('about_guild_report','About Guild Report','Guild Intelligence Source Map','Reference','registry','active',1,true,true,25,'Reference and provenance for the workbook-to-Command-Center migration.',array['guild_intelligence_page_registry']),
('relationships','Relationships','Member Relationships','People Intelligence','officer-managed','active',1,true,true,26,'Officer-managed social/relationship context between members.',array['guild_member_relationships']),
('echobase_platoons','EchoBase Platoons','EchoBase Platoons','External Operations','external','pending_source',5,true,true,27,'EchoBase-derived ROTE platoon assignments and fill state.',array['echobase_import']),
('echobase_ops_old','Echobase Ops- Old','EchoBase Operations Legacy','Legacy Operations','legacy-import','legacy_reference',6,true,false,28,'Legacy EchoBase Operations layout retained for historical mapping only.',array['legacy_workbook_import']),
('sheet40','Sheet40','Legacy Platoon Matrix','Legacy Operations','legacy-import','legacy_reference',6,true,false,29,'Legacy unit-to-platoon matrix retained as a migration/reference artifact.',array['legacy_workbook_import'])
on conflict (page_key) do update set
  workbook_sheet=excluded.workbook_sheet,
  title=excluded.title,
  category=excluded.category,
  source_kind=excluded.source_kind,
  implementation_status=excluded.implementation_status,
  phase=excluded.phase,
  daily_capture=excluded.daily_capture,
  user_facing=excluded.user_facing,
  sort_order=excluded.sort_order,
  description=excluded.description,
  expected_sources=excluded.expected_sources,
  updated_at=now();

insert into public.guild_intelligence_settings(guild_id)
select id from public.guilds
on conflict (guild_id) do nothing;

create or replace function public.guild_intelligence_capture_status(p_status text)
returns text
language sql
immutable
as $$
  select case p_status
    when 'active' then 'captured'
    when 'partial' then 'partial'
    when 'pending_source' then 'source_pending'
    when 'legacy_reference' then 'not_applicable'
    else 'failed'
  end
$$;

create or replace function public.guild_intelligence_page_payload(
  p_guild_id uuid,
  p_page_key text,
  p_report_date date,
  p_timezone text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  v_start timestamptz := (p_report_date::timestamp at time zone p_timezone);
  v_end timestamptz := ((p_report_date + 1)::timestamp at time zone p_timezone);
  v_payload jsonb;
begin
  if p_page_key = 'gr_dashboard' then
    select jsonb_build_object(
      'guild', jsonb_build_object('id', g.id, 'name', g.name, 'memberCount', g.member_count, 'galacticPower', g.galactic_power, 'characterPower', g.character_power, 'shipPower', g.ship_power, 'lastSyncedAt', g.last_synced_at),
      'snapshot', coalesce((select to_jsonb(gs) - 'guild_id' from public.guild_snapshots gs where gs.guild_id=p_guild_id order by gs.captured_at desc limit 1),'{}'::jsonb),
      'membershipEvents', coalesce((select jsonb_object_agg(event_type,cnt) from (select event_type,count(*) cnt from public.guild_membership_history where guild_id=p_guild_id and occurred_at>=v_start and occurred_at<v_end group by event_type) x),'{}'::jsonb),
      'activity', jsonb_build_object(
        'inactive24h', (select count(*) from (select distinct on (player_id) player_id,last_activity_at from public.guild_member_activity_snapshots where guild_id=p_guild_id order by player_id,captured_at desc) a where a.last_activity_at < now()-interval '24 hours'),
        'inactive48h', (select count(*) from (select distinct on (player_id) player_id,last_activity_at from public.guild_member_activity_snapshots where guild_id=p_guild_id order by player_id,captured_at desc) a where a.last_activity_at < now()-interval '48 hours')
      )
    ) into v_payload from public.guilds g where g.id=p_guild_id;
    return coalesce(v_payload,'{}'::jsonb);
  elsif p_page_key in ('member_data','tickets','ticket_dashboard') then
    select jsonb_build_object(
      'capturedFrom','latest-guild-member-activity',
      'members',coalesce(jsonb_agg(jsonb_build_object(
        'playerId',p.id,'allyCode',p.ally_code,'name',p.name,
        'galacticPower',gmc.member_galactic_power,'characterPower',gmc.member_character_power,'shipPower',gmc.member_ship_power,
        'guildJoinedAt',a.guild_joined_at,'lastActivityAt',a.last_activity_at,'memberLevel',a.member_level,'guildXp',a.guild_xp,
        'lifetimeSeasonScore',a.lifetime_season_score,'leagueId',a.league_id,'raidTicketsCurrent',a.raid_tickets_current,'raidTicketsLifetime',a.raid_tickets_lifetime,
        'memberContribution',coalesce(a.member_contribution,'[]'::jsonb),'seasonStatus',coalesce(a.season_status,'[]'::jsonb)
      ) order by p.name),'[]'::jsonb)
    ) into v_payload
    from public.guild_members_current gmc
    join public.players p on p.id=gmc.player_id
    left join lateral (
      select mas.* from public.guild_member_activity_snapshots mas
      where mas.guild_id=p_guild_id and mas.player_id=p.id
      order by mas.captured_at desc limit 1
    ) a on true
    where gmc.guild_id=p_guild_id;
    return coalesce(v_payload,'{}'::jsonb);
  elsif p_page_key = 'member_data_backup' then
    select jsonb_build_object('snapshotDate',p_report_date,'members',coalesce(jsonb_agg(to_jsonb(x) order by x.name),'[]'::jsonb)) into v_payload
    from (
      select p.ally_code,p.name,ps.galactic_power,ps.character_power,ps.ship_power,ps.character_count,ps.ship_count,ps.gl_count,ps.gear_13_count,ps.relic_5_plus_count,ps.relic_7_plus_count,ps.relic_9_count,ps.seven_star_ship_count,ps.zeta_count,ps.omicron_count,ps.ultimate_count,ps.omega_upgrade_count,ps.captured_at
      from public.player_snapshots ps join public.players p on p.id=ps.player_id
      where ps.guild_id=p_guild_id and ps.snapshot_date=p_report_date
    ) x;
    return coalesce(v_payload,jsonb_build_object('snapshotDate',p_report_date,'members','[]'::jsonb));
  elsif p_page_key = 'gl_report' then
    select jsonb_build_object('members',coalesce(jsonb_agg(member_row order by member_row->>'name'),'[]'::jsonb)) into v_payload
    from (
      select jsonb_build_object(
        'allyCode',p.ally_code,'name',p.name,
        'galacticLegends',coalesce((select jsonb_agg(jsonb_build_object('baseId',u.base_id,'name',gu.name,'rarity',u.rarity,'gearLevel',u.gear_level,'relicTier',u.relic_tier,'power',u.galactic_power,'ultimateUnlocked',u.ultimate_unlocked) order by gu.name)
          from public.player_units_current u join public.game_units gu on gu.base_id=u.base_id
          where u.player_id=p.id and 'galactic_legend'=any(gu.categories)),'[]'::jsonb)
      ) member_row
      from public.guild_members_current gmc join public.players p on p.id=gmc.player_id where gmc.guild_id=p_guild_id
    ) q;
    return coalesce(v_payload,'{}'::jsonb);
  elsif p_page_key = 'inquisitor_dashboard' then
    select jsonb_build_object('units',array['GRANDINQUISITOR','THIRDSISTER','FIFTHBROTHER','SEVENTHSISTER','EIGHTHBROTHER','NINTHSISTER','SECONDSISTER','MARROK'],
      'members',coalesce(jsonb_agg(member_row order by member_row->>'name'),'[]'::jsonb)) into v_payload
    from (
      select jsonb_build_object('allyCode',p.ally_code,'name',p.name,
        'inquisitors',coalesce((select jsonb_agg(jsonb_build_object('baseId',u.base_id,'name',gu.name,'rarity',u.rarity,'gearLevel',u.gear_level,'relicTier',u.relic_tier,'power',u.galactic_power) order by gu.name)
          from public.player_units_current u join public.game_units gu on gu.base_id=u.base_id
          where u.player_id=p.id and u.base_id=any(array['GRANDINQUISITOR','THIRDSISTER','FIFTHBROTHER','SEVENTHSISTER','EIGHTHBROTHER','NINTHSISTER','SECONDSISTER','MARROK'])),'[]'::jsonb)
      ) member_row
      from public.guild_members_current gmc join public.players p on p.id=gmc.player_id where gmc.guild_id=p_guild_id
    ) q;
    return coalesce(v_payload,'{}'::jsonb);
  elsif p_page_key = 'scorecards' then
    select jsonb_build_object('members',coalesce(jsonb_agg(jsonb_build_object(
      'allyCode',p.ally_code,'name',p.name,'galacticPower',gmc.member_galactic_power,'lastActivityAt',a.last_activity_at,'memberContribution',coalesce(a.member_contribution,'[]'::jsonb),
      'progressionEvents',(select count(*) from public.player_unit_progression_history ph where ph.guild_id=p_guild_id and ph.player_id=p.id and ph.changed_at>=v_start and ph.changed_at<v_end)
    ) order by p.name),'[]'::jsonb),'scope','partial-core-evidence') into v_payload
    from public.guild_members_current gmc join public.players p on p.id=gmc.player_id
    left join lateral (select mas.* from public.guild_member_activity_snapshots mas where mas.guild_id=p_guild_id and mas.player_id=p.id order by mas.captured_at desc limit 1) a on true
    where gmc.guild_id=p_guild_id;
    return coalesce(v_payload,'{}'::jsonb);
  elsif p_page_key = 'absences' then
    select jsonb_build_object('rows',coalesce(jsonb_agg(jsonb_build_object('id',a.id,'allyCode',p.ally_code,'name',p.name,'reason',a.reason,'startsAt',a.starts_at,'expectedReturnAt',a.expected_return_at,'actualReturnAt',a.actual_return_at,'status',a.status,'notes',a.notes) order by a.starts_at desc),'[]'::jsonb)) into v_payload
    from public.guild_member_absences a join public.players p on p.id=a.player_id where a.guild_id=p_guild_id;
    return coalesce(v_payload,'{}'::jsonb);
  elsif p_page_key = 'relationships' then
    select jsonb_build_object('rows',coalesce(jsonb_agg(jsonb_build_object('id',r.id,'allyCode',p.ally_code,'name',p.name,'relatedAllyCode',rp.ally_code,'relatedName',rp.name,'relationshipType',r.relationship_type,'label',r.label,'notes',r.notes) order by p.name,r.label),'[]'::jsonb)) into v_payload
    from public.guild_member_relationships r join public.players p on p.id=r.player_id left join public.players rp on rp.id=r.related_player_id where r.guild_id=p_guild_id;
    return coalesce(v_payload,'{}'::jsonb);
  elsif p_page_key = 'm_processing_cache' then
    return jsonb_build_object('guildId',p_guild_id,'reportDate',p_report_date,'latestGuildSnapshotId',(select id from public.guild_snapshots where guild_id=p_guild_id order by captured_at desc limit 1),'latestSyncRunId',(select id from public.guild_sync_runs where guild_id=p_guild_id and status='completed' order by completed_at desc limit 1));
  elsif p_page_key = 'about_guild_report' then
    return jsonb_build_object('sourceWorkbook','LV Unit Tracker (new)','migrationRule','Every workbook worksheet is registered in Guild Intelligence and receives a daily report-page record.');
  else
    select jsonb_build_object('workbookSheet',r.workbook_sheet,'title',r.title,'implementationStatus',r.implementation_status,'expectedSources',to_jsonb(r.expected_sources),'phase',r.phase,'description',r.description)
    into v_payload from public.guild_intelligence_page_registry r where r.page_key=p_page_key;
    return coalesce(v_payload,'{}'::jsonb);
  end if;
end
$$;

create or replace function public.capture_guild_intelligence_daily_report(
  p_guild_id uuid,
  p_report_date date,
  p_source_sync_job_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_settings public.guild_intelligence_settings%rowtype;
  v_report_id uuid;
  v_sync_run_id uuid;
  v_page record;
  v_captured int;
  v_partial int;
  v_pending int;
  v_na int;
  v_failed int;
  v_overall text;
begin
  select * into v_settings from public.guild_intelligence_settings where guild_id=p_guild_id;
  if not found then
    insert into public.guild_intelligence_settings(guild_id) values(p_guild_id) returning * into v_settings;
  end if;

  if p_source_sync_job_id is not null then
    select sync_run_id into v_sync_run_id from public.guild_sync_jobs where id=p_source_sync_job_id and guild_id=p_guild_id;
  end if;
  if v_sync_run_id is null then
    select id into v_sync_run_id from public.guild_sync_runs where guild_id=p_guild_id and status='completed' order by completed_at desc nulls last limit 1;
  end if;

  insert into public.guild_intelligence_daily_reports(guild_id,report_date,report_timezone,scheduled_local_time,status,source_sync_job_id,source_sync_run_id,captured_at,updated_at)
  values(p_guild_id,p_report_date,v_settings.report_timezone,v_settings.report_local_time,'capturing',p_source_sync_job_id,v_sync_run_id,now(),now())
  on conflict (guild_id,report_date) do update set report_timezone=excluded.report_timezone,scheduled_local_time=excluded.scheduled_local_time,status='capturing',source_sync_job_id=coalesce(excluded.source_sync_job_id,public.guild_intelligence_daily_reports.source_sync_job_id),source_sync_run_id=coalesce(excluded.source_sync_run_id,public.guild_intelligence_daily_reports.source_sync_run_id),captured_at=now(),error_message=null,updated_at=now()
  returning id into v_report_id;

  for v_page in select * from public.guild_intelligence_page_registry where daily_capture order by sort_order loop
    begin
      insert into public.guild_intelligence_daily_pages(report_id,guild_id,report_date,page_key,capture_status,captured_at,source_sync_run_id,payload,metrics,error_message)
      values(v_report_id,p_guild_id,p_report_date,v_page.page_key,public.guild_intelligence_capture_status(v_page.implementation_status),now(),v_sync_run_id,public.guild_intelligence_page_payload(p_guild_id,v_page.page_key,p_report_date,v_settings.report_timezone),jsonb_build_object('implementationStatus',v_page.implementation_status,'phase',v_page.phase),null)
      on conflict (report_id,page_key) do update set capture_status=excluded.capture_status,captured_at=excluded.captured_at,source_sync_run_id=excluded.source_sync_run_id,payload=excluded.payload,metrics=excluded.metrics,error_message=null;
    exception when others then
      insert into public.guild_intelligence_daily_pages(report_id,guild_id,report_date,page_key,capture_status,captured_at,source_sync_run_id,payload,metrics,error_message)
      values(v_report_id,p_guild_id,p_report_date,v_page.page_key,'failed',now(),v_sync_run_id,'{}'::jsonb,jsonb_build_object('implementationStatus',v_page.implementation_status,'phase',v_page.phase),left(sqlerrm,1000))
      on conflict (report_id,page_key) do update set capture_status='failed',captured_at=excluded.captured_at,error_message=excluded.error_message;
    end;
  end loop;

  select count(*) filter(where capture_status='captured'),count(*) filter(where capture_status='partial'),count(*) filter(where capture_status='source_pending'),count(*) filter(where capture_status='not_applicable'),count(*) filter(where capture_status='failed')
  into v_captured,v_partial,v_pending,v_na,v_failed from public.guild_intelligence_daily_pages where report_id=v_report_id;
  v_overall := case when v_failed>0 then 'failed' when v_partial>0 or v_pending>0 then 'partial' else 'completed' end;

  update public.guild_intelligence_daily_reports set status=v_overall,completed_at=now(),summary=jsonb_build_object('totalPages',v_captured+v_partial+v_pending+v_na+v_failed,'captured',v_captured,'partial',v_partial,'sourcePending',v_pending,'notApplicable',v_na,'failed',v_failed,'returnedEvents',(select count(*) from public.guild_membership_history where guild_id=p_guild_id and event_type='returned' and occurred_at>=p_report_date::timestamp at time zone v_settings.report_timezone and occurred_at<(p_report_date+1)::timestamp at time zone v_settings.report_timezone)),updated_at=now() where id=v_report_id;

  update public.guild_intelligence_settings set last_completed_report_date=p_report_date,last_completed_at=now(),last_error=case when v_failed>0 then 'One or more Guild Intelligence pages failed capture.' else null end,updated_at=now() where guild_id=p_guild_id;
  return v_report_id;
end
$$;

create or replace function public.read_guild_intelligence_status(p_ally_code text)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  v_code text := regexp_replace(coalesce(p_ally_code,''),'[^0-9]','','g');
  v_guild_id uuid;
  v_report_id uuid;
  v_result jsonb;
begin
  if length(v_code)<>9 then return null; end if;
  select p.current_guild_id into v_guild_id from public.players p where p.ally_code=v_code limit 1;
  if v_guild_id is null then return null; end if;
  select id into v_report_id from public.guild_intelligence_daily_reports where guild_id=v_guild_id order by report_date desc,captured_at desc nulls last limit 1;
  select jsonb_build_object(
    'guild',jsonb_build_object('id',g.id,'name',g.name,'memberCount',g.member_count,'galacticPower',g.galactic_power,'lastSyncedAt',g.last_synced_at),
    'settings',coalesce((select to_jsonb(s)-'guild_id' from public.guild_intelligence_settings s where s.guild_id=v_guild_id),'{}'::jsonb),
    'latestReport',coalesce((select to_jsonb(r)-'guild_id' from public.guild_intelligence_daily_reports r where r.id=v_report_id),'null'::jsonb),
    'returnedTotal',(select count(*) from public.guild_membership_history mh where mh.guild_id=v_guild_id and mh.event_type='returned'),
    'pages',coalesce((select jsonb_agg(jsonb_build_object('pageKey',reg.page_key,'workbookSheet',reg.workbook_sheet,'title',reg.title,'category',reg.category,'sourceKind',reg.source_kind,'implementationStatus',reg.implementation_status,'phase',reg.phase,'dailyCapture',reg.daily_capture,'userFacing',reg.user_facing,'sortOrder',reg.sort_order,'description',reg.description,'expectedSources',to_jsonb(reg.expected_sources),'captureStatus',dp.capture_status,'capturedAt',dp.captured_at,'metrics',coalesce(dp.metrics,'{}'::jsonb),'error',dp.error_message) order by reg.sort_order) from public.guild_intelligence_page_registry reg left join public.guild_intelligence_daily_pages dp on dp.report_id=v_report_id and dp.page_key=reg.page_key),'[]'::jsonb)
  ) into v_result from public.guilds g where g.id=v_guild_id;
  return v_result;
end
$$;

create or replace function public.ensure_guild_intelligence_settings()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  insert into public.guild_intelligence_settings(guild_id) values(new.id) on conflict(guild_id) do nothing;
  return new;
end
$$;

drop trigger if exists guilds_intelligence_settings on public.guilds;
create trigger guilds_intelligence_settings after insert on public.guilds for each row execute function public.ensure_guild_intelligence_settings();

alter table public.guild_intelligence_page_registry enable row level security;
alter table public.guild_intelligence_settings enable row level security;
alter table public.guild_intelligence_daily_reports enable row level security;
alter table public.guild_intelligence_daily_pages enable row level security;
alter table public.guild_member_absences enable row level security;
alter table public.guild_member_relationships enable row level security;

revoke all on public.guild_intelligence_page_registry,public.guild_intelligence_settings,public.guild_intelligence_daily_reports,public.guild_intelligence_daily_pages,public.guild_member_absences,public.guild_member_relationships from anon,authenticated;
grant select,insert,update,delete on public.guild_intelligence_page_registry,public.guild_intelligence_settings,public.guild_intelligence_daily_reports,public.guild_intelligence_daily_pages,public.guild_member_absences,public.guild_member_relationships to service_role;
grant usage,select on sequence public.guild_intelligence_daily_pages_id_seq to service_role;
revoke all on function public.guild_intelligence_capture_status(text) from public,anon,authenticated;
revoke all on function public.guild_intelligence_page_payload(uuid,text,date,text) from public,anon,authenticated;
revoke all on function public.capture_guild_intelligence_daily_report(uuid,date,uuid) from public,anon,authenticated;
revoke all on function public.read_guild_intelligence_status(text) from public,anon,authenticated;
grant execute on function public.guild_intelligence_capture_status(text) to service_role;
grant execute on function public.guild_intelligence_page_payload(uuid,text,date,text) to service_role;
grant execute on function public.capture_guild_intelligence_daily_report(uuid,date,uuid) to service_role;
grant execute on function public.read_guild_intelligence_status(text) to service_role;